import { SheriffConfig } from '@softarc/sheriff-core';

// noinspection JSUnusedGlobalSymbols
export const sheriffConfig: SheriffConfig = {
  version: 1,
  tagging: {
    'src/app/settings': ['settings'],
    'src/app/analysis/changes': ['analysis/changes'],
    'src/app/analysis/route': ['analysis/route'],
    'src/app/analysis/network': ['analysis/network'],
    'src/app/analysis/overview': ['analysis/overview'],
    'src/app/analysis/node': ['analysis/node'],
    'src/app/analysis/facts': ['analysis/facts'],
    'src/app/analysis/analysis': ['analysis/analysis'],
    'src/app/analysis/subset': ['analysis/subset'],
    'src/app/analysis/strategy': ['analysis/strategy'],
    'src/app/analysis/components/changes/route': [
      'analysis/components/changes/route',
    ],
    'src/app/analysis/components/changes/node': [
      'analysis/components/changes/node',
    ],
    'src/app/analysis/components/changes/filter': [
      'analysis/components/changes/filter',
    ],
    'src/app/analysis/components/changes': ['analysis/components/changes'],
    'src/app/analysis/components/indicators/route': [
      'analysis/components/indicators/route',
    ],
    'src/app/analysis/components/change-set/components': [
      'analysis/components/change-set/components',
    ],
    'src/app/analysis/components/change-set': [
      'analysis/components/change-set',
    ],
    'src/app/analysis/components/filter': ['analysis/components/filter'],
    'src/app/analysis/components/edit': ['analysis/components/edit'],
    'src/app/analysis/components': ['analysis/components'],
    'src/app/analysis/fact': ['analysis/fact'],
    'src/app/analysis/changeset': ['analysis/changeset'],
    'src/app/analysis/location': ['analysis/location'],
    'src/app/planner': ['planner'],
    'src/app/status': ['status'],
    'src/app/base': ['base'],
    'src/app/spinner': ['spinner'],
    'src/app/core': ['core'],
    'src/app/poi': ['poi'],
    'src/app/demo': ['demo'],
    'src/app/services': ['services'],
    'src/app/util': ['util'],

    'src/app/components/shared/tags': ['components/shared/tags'],
    'src/app/components/shared/json': ['components/shared/json'],
    'src/app/components/shared/link': ['components/shared/link'],
    'src/app/components/shared/items': ['components/shared/items'],
    'src/app/components/shared/day': ['components/shared/day'],
    'src/app/components/shared/dialog': ['components/shared/dialog'],
    'src/app/components/shared/paginator': ['components/shared/paginator'],
    'src/app/components/shared/toolbar': ['components/shared/toolbar'],
    'src/app/components/shared/icon': ['components/shared/icon'],
    'src/app/components/shared/indicator': ['components/shared/indicator'],
    'src/app/components/shared/error': ['components/shared/error'],
    'src/app/components/shared/data': ['components/shared/data'],
    'src/app/components/shared/page': ['components/shared/page'],
    'src/app/components/shared/format': ['components/shared/format'],
    'src/app/components/shared/timestamp': ['components/shared/timestamp'],
    'src/app/components/shared/sidebar': ['components/shared/sidebar'],
    'src/app/components/shared/menu': ['components/shared/menu'],
    'src/app/components/shared': ['components/shared'],
    'src/app/components/poi': ['components/poi'],

    'src/app/components': {
      'ol/layers': ['ol'],
      'ol/style': ['ol'],
      'ol/services': ['ol'],
      'ol/components': ['ol'],
      'ol/domain': ['ol'],
      ol: ['ol'],
    },

    'src/app/friso': ['friso'],
    'src/app/i18n': ['i18n'],
    'src/app/monitor': ['monitor'],
    'src/app/kpn/common': ['kpn/common'],
    'src/app/kpn/filter': ['kpn/filter'],

    'src/app/kpn/api': {
      'common/common': ['api'],
      'common/tiles': ['api'],
      'common/changes/details': ['api'],
      'common/changes/filter': ['api'],
      'common/changes': ['api'],
      'common/route': ['api'],
      'common/network': ['api'],
      'common/node': ['api'],
      'common/statistics': ['api'],
      'common/planner': ['api'],
      'common/diff/common': ['api'],
      'common/diff/route': ['api'],
      'common/diff/network': ['api'],
      'common/diff/node': ['api'],
      'common/diff': ['api'],
      'common/status': ['api'],
      'common/subset': ['api'],
      'common/poi': ['api'],
      'common/data/raw': ['api'],
      'common/data': ['api'],
      'common/monitor': ['api'],
      'common/location': ['api'],
      common: ['api'],
      custom: ['api'],
    },
    'src/app': ['app'],
  },
  depRules: {
    app: ['*'],
    api: ['api'],
    ol: [
      'ol',
      'api',
      'util',
      'components/shared', // depends on PageService
      'i18n', // layer name translations, replace with $localize locally
      'kpn/common', // depends on UniqueId, move to 'util' ?
      'services', // depends on PoiTileLayerService depends on PoiService
      'core', // MainMapStyleParameters and SurveyDateStyle depend on SurveyDateValues
    ],
    settings: ['core', 'components/shared'],
    'analysis/changes': [
      'api',
      'base',
      'ol',
      'core',
      'i18n',
      'util',
      'kpn/common',
      'kpn/filter',
      'services',
      'analysis/strategy',
      'analysis/components',
      'analysis/components/changes/filter',
      'components/shared',
      'components/shared/paginator',
      'components/shared/tags',
    ],
    'analysis/route': [
      'api',
      'base',
      'ol',
      'core',
      'i18n',
      'kpn/common',
      'services',
      'analysis/components',
      'analysis/fact',
      'components/shared',
      'components/shared/sidebar',
      'components/shared/tags',
    ],
    'analysis/network': [
      'api',
      'base',
      'ol',
      'core',
      'kpn/common',
      'kpn/filter',
      'services',
      'analysis/components',
      'analysis/components/edit',
      'analysis/fact',
      'components/shared',
      'components/shared/indicator',
      'components/shared/sidebar',
      'components/shared/tags',
    ],
    'analysis/overview': ['api', 'components/shared', 'kpn/common', 'services'],
    'analysis/node': [
      'api',
      'base',
      'ol',
      'core',
      'i18n',
      'kpn/common',
      'services',
      'analysis/components',
      'analysis/fact',
      'components/shared',
      'components/shared/sidebar',
      'components/shared/tags',
    ],
    'analysis/facts': [
      'api',
      'analysis/fact',
      'components/shared',
      'components/shared/sidebar',
    ],
    'analysis/analysis': [
      'api',
      'base',
      'ol',
      'core',
      'i18n',
      'util',
      'services',
      'kpn/common',
      'kpn/filter',
      'analysis/components',
      'analysis/components/edit',
      'analysis/fact',
      'analysis/strategy',
      'components/shared',
      'components/shared/indicator',
      'components/shared/paginator',
      'components/shared/sidebar',
      'components/shared/tags',
      'components/shared',
    ],
    'analysis/subset': [
      'api',
      'base',
      'ol',
      'core',
      'i18n',
      'kpn/common',
      'kpn/filter',
      'services',
      'analysis/components',
      'analysis/components/edit',
      'analysis/fact',
      'analysis/strategy',
      'components/shared',
    ],
    'analysis/strategy': ['core', 'components/shared'],
    'analysis/components/changes/route': [
      'api',
      'ol',
      'i18n',
      'components/shared',
      'components/shared/tags',
    ],
    'analysis/components/changes/node': [
      'api',
      'ol',
      'components/shared',
      'components/shared/tags',
    ],
    'analysis/components/changes': ['api', 'components/shared'],
    'analysis/components/changes/filter': [
      'api',
      'kpn/common',
      'components/shared',
    ],
    'analysis/components/indicators/route': ['api'],
    'analysis/components': [
      'ol',
      'components/shared',
      'analysis/fact',
      'analysis/strategy',
      'analysis/components/changes/route',
      'analysis/components/changes/node',
      'analysis/components/changes',
      'analysis/components/changes/filter',
      'analysis/components/indicators/route',
      'analysis/components/change-set',
      'analysis/components/change-set/components',
      'analysis/components/filter',
      'analysis/components/edit',
    ],
    'analysis/components/change-set': [
      'api',
      'i18n',
      'components/shared',
      'analysis/components/change-set/components',
    ],
    'analysis/components/change-set/components': ['api'],
    'analysis/components/filter': ['i18n', 'kpn/filter'],
    'analysis/components/edit': [
      'api',
      'core',
      'util',
      'services',
      'components/shared/paginator',
    ],
    'analysis/fact': ['api', 'components/shared'],
    'analysis/changeset': [
      'api',
      'ol',
      'core',
      'i18n',
      'util',
      'kpn/common',
      'kpn/filter',
      'services',
      'analysis/components',
      'components/shared',
      'components/shared/paginator',
      'components/shared/sidebar',
      'components/shared/tags',
    ],
    'analysis/location': [
      'api',
      'ol',
      'core',
      'util',
      'services',
      'kpn/common',
      'analysis/components',
      'analysis/components/edit',
      'analysis/fact',
      'analysis/strategy',
      'components/shared',
      'components/shared/indicator',
      'components/shared/paginator',
    ],
    planner: [
      'api',
      'base',
      'ol',
      'core',
      'i18n',
      'kpn/common',
      'util',
      'services',
      'components/poi',
      'components/shared',
      'components/shared/tags',
    ],
    status: ['api', 'components/shared', 'services'],
    base: ['api', 'core', 'kpn/common', 'spinner', 'components/shared'],
    spinner: ['core'],
    core: [
      'api', // "@api/common" in "shared/survey-date-values.ts"
      'analysis/components/edit', // EditParameters in shared.actions.ts and shared/shared.effects.ts
      'components/shared', //   in "preferences/preferences.reducer.ts"
      'components/shared/format', // DayPipe referenced in SurveyDateValues
      'core', // in "user/user.effects.ts"
      'services', // in "shared/shared.effects.ts" and "user/user.effects.ts"
    ],
    poi: [
      'api',
      'core',
      'base',
      'ol',
      'i18n',
      'kpn/common',
      'services',
      'util',
      'analysis/components',
      'analysis/location',
      'components/poi',
      'components/shared',
      'components/shared/paginator',
      'components/shared/tags',
    ],
    demo: ['core', 'components/shared'],
    services: ['api', 'ol', 'core'],
    util: [],
    'components/shared/tags': ['api', 'kpn/common'],
    'components/shared/json': [],
    'components/shared/link': ['api', 'core', 'i18n', 'services'],
    'components/shared': [
      'api',
      'i18n',
      'services',
      'spinner',
      'components/shared/data',
      'components/shared/day',
      'components/shared/dialog',
      'components/shared/error',
      'components/shared/format',
      'components/shared/icon',
      'components/shared/indicator',
      'components/shared/items',
      'components/shared/json',
      'components/shared/link',
      'components/shared/menu',
      'components/shared/page',
      'components/shared/paginator',
      'components/shared/sidebar',
      'components/shared/tags',
      'components/shared/timestamp',
      'components/shared/toolbar',
    ],
    'components/shared/items': [],
    'components/shared/day': ['api'],
    'components/shared/dialog': [],
    'components/shared/paginator': [],
    'components/shared/toolbar': [
      'api',
      'i18n',
      'kpn/common',
      'services',
      'spinner',
      'components/shared',
    ],
    'components/shared/icon': [],
    'components/shared/indicator': ['api', 'kpn/common'],
    'components/shared/error': ['core'],
    'components/shared/data': [],
    'components/shared/page': ['i18n', 'services'],
    'components/shared/format': [
      'api',
      'core',
      'i18n',
      'kpn/common',
      'services',
      'spinner',
      'components/shared',
    ],
    'components/shared/timestamp': ['api'],
    'components/shared/sidebar': [
      'api',
      'core',
      'i18n',
      'kpn/common',
      'services',
      'spinner',
      'components/shared',
    ],
    'components/shared/menu': [],
    'components/poi': [
      'api',
      'core',
      'i18n',
      'kpn/common',
      'services',
      'spinner',
      'components/shared',
    ],
    friso: ['api', 'ol', 'core', 'components/shared'],
    i18n: [],
    monitor: [
      'api',
      'ol',
      'core',
      'util',
      'analysis/components/edit', // EditParameters?
      'components/shared',
      'components/shared/sidebar',
    ],
    'kpn/common': ['api'],
    'kpn/filter': ['api', 'kpn/common'],
  },
};
