import { SheriffConfig } from '@softarc/sheriff-core';

export const sheriffConfig: SheriffConfig = {
  version: 1,
  tagging: {
    // 'src/app': {
    //   shared: {
    //     'feature-<feature>': ['shared', 'type:feature'],
    //     'ui-<ui>': ['shared', 'type:ui'],
    //     data: ['shared', 'type:data'],
    //     'util-<ui>': ['shared', 'type:util'],
    //   },
    //   'domains/<domain>': {
    //     'feature-<feature>': ['domain:<domain>', 'type:feature'],
    //     'ui-<ui>': ['domain:<domain>', 'type:ui'],
    //     data: ['domain:<domain>', 'type:data'],
    //     'util-<ui>': ['domain:<domain>', 'type:util'],
    //   },
    'src/app/settings': ['settings'],
    'src/app/analysis/changes': ['analysis/changes'],
    'src/app/analysis/route': ['analysis/route'],
    'src/app/analysis/network': ['analysis/network'],
    'src/app/analysis/overview': ['analysis/overview'],
    'src/app/analysis/node': ['analysis/node'],
    'src/app/analysis/facts': ['analysis/facts'],
    'src/app/analysis/analysis': ['analysis/analysis'],
    'src/app/analysis/subset': ['analysis/subset'],
    'src/app/analysis/strategy': ['analysis/strategy'],
    'src/app/analysis/components/changes/route': [
      'analysis/components/changes/route',
    ],
    'src/app/analysis/components/changes/node': [
      'analysis/components/changes/node',
    ],
    'src/app/analysis/components/changes/filter': [
      'analysis/components/changes/filter',
    ],
    'src/app/analysis/components/changes': ['analysis/components/changes'],
    'src/app/analysis/components/indicators/route': [
      'analysis/components/indicators/route',
    ],
    'src/app/analysis/components/change-set/components': [
      'analysis/components/change-set/components',
    ],
    'src/app/analysis/components/change-set': [
      'analysis/components/change-set',
    ],
    'src/app/analysis/components/filter': ['analysis/components/filter'],
    'src/app/analysis/components/edit': ['analysis/components/edit'],
    'src/app/analysis/components': ['analysis/components'],
    'src/app/analysis/fact': ['analysis/fact'],
    'src/app/analysis/changeset': ['analysis/changeset'],
    'src/app/analysis/location': ['analysis/location'],
    'src/app/planner': ['planner'],
    'src/app/status': ['status'],
    'src/app/base': ['base'],
    'src/app/spinner': ['spinner'],
    'src/app/core/router': ['core/router'],
    'src/app/core/preferences': ['core/preferences'],
    'src/app/core/shared': ['core/shared'],
    'src/app/core/page': ['core/page'],
    'src/app/core/user': ['core/user'],
    'src/app/core': ['core'],
    'src/app/poi': ['poi'],
    'src/app/demo': ['demo'],
    'src/app/services': ['services'],
    'src/app/util': ['util'],
    'src/app/components/ol/layers': ['components/ol/layers'],
    'src/app/components/ol/style': ['components/ol/style'],
    'src/app/components/ol/services': ['components/ol/services'],
    'src/app/components/ol/components': ['components/ol/components'],
    'src/app/components/ol/domain': ['components/ol/domain'],
    'src/app/components/ol': ['components/ol'],
    'src/app/components/shared/tags': ['components/shared/tags'],
    'src/app/components/shared/json': ['components/shared/json'],
    'src/app/components/shared/link': ['components/shared/link'],
    'src/app/components/shared/items': ['components/shared/items'],
    'src/app/components/shared/day': ['components/shared/day'],
    'src/app/components/shared/dialog': ['components/shared/dialog'],
    'src/app/components/shared/paginator': ['components/shared/paginator'],
    'src/app/components/shared/toolbar': ['components/shared/toolbar'],
    'src/app/components/shared/icon': ['components/shared/icon'],
    'src/app/components/shared/indicator': ['components/shared/indicator'],
    'src/app/components/shared/error': ['components/shared/error'],
    'src/app/components/shared/data': ['components/shared/data'],
    'src/app/components/shared/page': ['components/shared/page'],
    'src/app/components/shared/format': ['components/shared/format'],
    'src/app/components/shared/timestamp': ['components/shared/timestamp'],
    'src/app/components/shared/sidebar': ['components/shared/sidebar'],
    'src/app/components/shared/menu': ['components/shared/menu'],
    'src/app/components/shared': ['components/shared'],
    'src/app/components/poi': ['components/poi'],
    'src/app/friso': ['friso'],
    'src/app/i18n': ['i18n'],
    'src/app/monitor': ['monitor'],
    'src/app/kpn/common': ['kpn/common'],
    'src/app/kpn/filter': ['kpn/filter'],

    'src/app/kpn/api': {
      'common/common': ['api'],
      'common/tiles': ['api'],
      'common/changes/details': ['api'],
      'common/changes/filter': ['api'],
      'common/changes': ['api'],
      'common/route': ['api'],
      'common/network': ['api'],
      'common/node': ['api'],
      'common/statistics': ['api'],
      'common/planner': ['api'],
      'common/diff/common': ['api'],
      'common/diff/route': ['api'],
      'common/diff/network': ['api'],
      'common/diff/node': ['api'],
      'common/diff': ['api'],
      'common/status': ['api'],
      'common/subset': ['api'],
      'common/poi': ['api'],
      'common/data/raw': ['api'],
      'common/data': ['api'],
      'common/monitor': ['api'],
      'common/location': ['api'],
      common: ['api'],
      custom: ['api'],
    },
    'src/app': ['app'],
    // },
  },
  depRules: {
    api: ['api'],
    root: ['*'],
    app: ['*'],
    settings: ['*'],
    'analysis/changes': ['*'],
    'analysis/route': ['*'],
    'analysis/network': ['*'],
    'analysis/overview': ['*'],
    'analysis/node': ['*'],
    'analysis/facts': ['*'],
    'analysis/analysis': ['*'],
    'analysis/subset': ['*'],
    'analysis/strategy': ['*'],
    'analysis/components/changes/route': ['*'],
    'analysis/components/changes/node': ['*'],
    'analysis/components/changes': ['*'],
    'analysis/components/changes/filter': ['*'],
    'analysis/components/indicators/route': ['*'],
    'analysis/components': ['*'],
    'analysis/components/change-set': ['*'],
    'analysis/components/change-set/components': ['*'],
    'analysis/components/filter': ['*'],
    'analysis/components/edit': ['*'],
    'analysis/fact': ['*'],
    'analysis/changeset': ['*'],
    'analysis/location': ['*'],
    planner: ['*'],
    status: ['*'],
    base: ['*'],
    spinner: ['*'],
    'core/router': ['*'],
    core: ['*'],
    'core/preferences': ['*'],
    'core/shared': ['*'],
    'core/page': ['*'],
    'core/user': ['*'],
    poi: ['*'],
    demo: ['*'],
    services: ['*'],
    util: ['*'],
    'components/ol/layers': ['*'],
    'components/ol': ['*'],
    'components/ol/style': ['*'],
    'components/ol/services': ['*'],
    'components/ol/components': ['*'],
    'components/ol/domain': ['*'],
    'components/shared/tags': ['*'],
    'components/shared/json': ['*'],
    'components/shared/link': ['*'],
    'components/shared': ['*'],
    'components/shared/items': ['*'],
    'components/shared/day': ['*'],
    'components/shared/dialog': ['*'],
    'components/shared/paginator': ['*'],
    'components/shared/toolbar': ['*'],
    'components/shared/icon': ['*'],
    'components/shared/indicator': ['*'],
    'components/shared/error': ['*'],
    'components/shared/data': ['*'],
    'components/shared/page': ['*'],
    'components/shared/format': ['*'],
    'components/shared/timestamp': ['*'],
    'components/shared/sidebar': ['*'],
    'components/shared/menu': ['*'],
    'components/poi': ['*'],
    friso: ['*'],
    i18n: ['*'],
    monitor: ['*'],
    'kpn/common': ['*'],
    'kpn/filter': ['*'],
    // 'domain:*': [sameTag, 'shared'],
    // 'shared': ['shared'],
    // 'type:feature': ['type:ui', 'type:data', 'type:util'],
    // 'type:ui': ['type:data', 'type:util'],
    // 'type:data': ['type:util'],
    // 'type:util': noDependencies
  },
};
