== Analysis

=== Mapping


==== Network types

rwn

__R__egional __W__alking __N__etwork


rcn


__R__egional __C__ycle __N__etwork


rhn

rmn

rpn

rin


==== Node

...


==== Route relation


Relation with node and route members.

A walking network relation has the following required tags:

[cols="1,1,4"]
|===
|Tag|Value|Comment

|network
|rwn
|rwn = regional walking network

|type
|network
|

|name
|_name_
|network name
|===

A cycle network relation has the following required tags:

[cols="1,1,4"]
|===
|Tag|Value|Comment

|network
|rcn
|rcn = regional cycle network

|type
|network
|

|name
|_name_
|network name
|===


The route name is expected to include the start network node name and the end network node name
separated by a dash. Example: _23-68_ for the route between start node _23_ and end node _68_.


The route relation contains the ways connecting the network nodes, and optionally also
the network nodes themselves.

A walking network route relation has the following required tags:


[cols="1,1,4"]
|===
|Tag|Value| Comment

| network
| rwn
| rwn = regional walking network

| type
| route
|

| route
| foot
| Instead of _foot_, the analyzer also allows _hiking_ and _walking_.

| note
| _name_
| The route name is expected to include the start network node name and the end network node name
separated by a dash. Example: _23-68_ for the route between start node _23_ and end node _68_.
|===

A bicyle network route relation has the following required tags:

[cols="1,1,4"]
|===
|Tag|Value|Comment

| network
| rcn
| rcn = regional cycle network

|type
|route
|

|route
|bicycle
|

|note
|_name_
|route name
|===



==== Network relation

Relation with node and route members.

A walking network relation has the following required tags:

[cols="1,1,4"]
|===
|Tag|Value|Comment

|network
|rwn
|rwn = regional walking network

|type
|network
|

|name
|_name_
|network name
|===

A cycle network relation has the following required tags:

[cols="1,1,4"]
|===
|Tag|Value|Comment

|network
|rcn
|rcn = regional cycle network

|type
|network
|

|name
|_name_
|network name
|===


==== Orphan nodes

An orphan node is a network node without a known network that is belongs to.

We can see that the node is a network node because it has the required *"rwn_ref"* or
*"rcn_ref"* tag, but the node was not added as a member to a known network relation,
and also not added as a member to known route relation that itself was added as a member
to a known network relation.

If there is something wrong the relation that the node is added to (for example when that
relation is not following the rules for a valid network or route relation), then the network
node is also considered _"orphan"_.



==== Orphan routes

An orphan route is a network route without a known network that is belongs to.

We can see that the relation represents a network route because it has the required tags,
but the relation was not added as a member to a known network relation.

If there is something wrong the relation that the route is added to, then the route is
also considered _"orphan"_.



==== Information map

Information maps are situated along the network routes and provide an overview
of the network. They can be mapped using nodes that can be optionally be added
to the network relation. The analysis logic expects at least the following tags
on the node to recognize it as an information map:

[cols="1,4"]
|===
|Tag|Value

|tourism
|information

|information
|map
|===


==== Accessible

The analyzer tries to determine whether the routes as defined in the network are actually
accessible for the user for which the network is intended.

The validation rules for hiking-, bicycle-, horse- and skateroutes dictate that one of the
following is true for each way in the route relation for the route to be considered _"accessible"_:

* The way has a value for tag _"highway"_ or _"highway:virtual"_.
* The way has tag _"route"_ with value _"ferry"_.
* The way in the bicycle network has tag _"bicycle"_ with value _"yes"_.
* The way in the hiking network has tag _"foot"_ with value _"yes"_.
* The way in the horse network has tag _"horse"_ with value _"yes"_.
* The way in the skate network has tag _"inline_skates"_ with value _"yes"_.

Motorboat network:

* The way has a tag with key _"waterway"_ or  _"waterway:virtual"_.

Canoe network, at least 1 of:

* The way has a tag with key  _"waterway"_ or _"waterway:virtual"_.
* The way has a tag with key  _"canoe"_ and value  _"yes"_.
* The way has a tag with key  _"canoe"_ and value _"portage"_.


=== Analysis pages in the application


[#login-page]
==== Login


[#logout-page]
==== Logout



[#overview-in-numbers-page]
==== Overview in numbers


[#changes-page]
==== Network changes


[#subset-page]
==== Subset

country / network type


[#subset-networks-page]
===== Subset networks


[#subset-facts-page]
===== Subset facts


[#subset-orphan-nodes-page]
===== Subset orphan nodes


[#subset-orphan-routes-page]
===== Subset orphan routes


[#subset-changes-page]
===== Subset changes



[#network-page]
==== Network

- Network details


- Network map


- Network changes


[#route-page]
==== Route

- Route details

- Route map

- Route changes


[#node-page]
==== Node

- Node details

- Node map

- Node changes
