package kpn.tools.code

import kpn.tools.code.codecs.Codecs
import kpn.tools.code.domain.ClassInfo

import java.io.File
import java.io.PrintStream

class CodecProviderWriter {

  def write(classInfos: Seq[ClassInfo]): Unit = {

    val file = new File(s"${Codecs.OutputDir}/_CodecProvider.scala")
    file.getParentFile.mkdirs()

    val out = new IndentingPrintStream(new PrintStream(file))

    try {
      writeHeader(out)
      writeImports(out, classInfos)

      out.skipLine()
      out.println(s"class _CodecProvider extends CodecProvider {")
      out.indent {
        out.println(s"override def get[T](aClass: Class[T], codecRegistry: CodecRegistry): Codec[T] = {")
        out.indent {
          writeCodecs(out, classInfos)
          out.println("null")
        }
        out.println(s"}")
      }
      out.println("}")
    }
    finally {
      out.close()
    }
  }

  private def createOutputFile(classInfo: ClassInfo): File = {
    val file = new File(s"${Codecs.OutputDir}/${classInfo.className}Codec.scala")
    file.getParentFile.mkdirs()
    file
  }

  private def writeHeader(out: IndentingPrintStream): Unit = {
    out.println("// this file is generated by kpn.tools.code.CodecProviderWriter")
    out.skipLine()
    out.println("package kpn.tools.code.codecs.generated")
  }

  private def writeImports(out: IndentingPrintStream, classInfos: Seq[ClassInfo]): Unit = {
    val fixedImportClasses = Seq(
      "org.bson.codecs.Codec",
      "org.bson.codecs.configuration.CodecProvider",
      "org.bson.codecs.configuration.CodecRegistry",
      "kpn.tools.code.codecs.DayCodec",
      "kpn.tools.code.codecs.RelationCodec",
      "kpn.tools.code.codecs.TagCodec",
      "kpn.tools.code.codecs.TimestampCodec",
      "kpn.tools.code.codecs.ScalaLongCodec",
    )

    val classInfosImportClasses = classInfos.map(classInfo => classInfo.key)

    val importClasses = (fixedImportClasses ++ classInfosImportClasses).sorted.distinct

    out.skipLine()
    importClasses.foreach { className =>
      out.println(s"import $className")
    }
  }

  private def writeCodecs(out: IndentingPrintStream, classInfos: Seq[ClassInfo]): Unit = {
    out.skipLine()
    out.println(s"if (aClass == classOf[Long]) {")
    out.indent {
      out.println(s"return new ScalaLongCodec(codecRegistry).asInstanceOf[Codec[T]]")
    }
    out.println(s"}")
    out.skipLine()
    classInfos.foreach { classInfo =>
      out.println(s"if (aClass == classOf[${classInfo.className}]) {")
      out.indent {
        out.println(s"return new ${classInfo.className}Codec(codecRegistry).asInstanceOf[Codec[T]]")
      }
      out.println(s"}")
    }
  }
}
