import { ChangeDetectionStrategy } from '@angular/core';
import { Component, Input } from '@angular/core';
import { Fact } from '@api/custom/fact';

@Component({
  selector: 'kpn-fact-name',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ng-container [ngSwitch]="fact">
      <ng-container i18n="@@fact.name.added" *ngSwitchCase="'Added'"
        ><span>Added</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.become-orphan"
        *ngSwitchCase="'BecomeOrphan'"
        ><span>BecomeOrphan</span>
      </ng-container>
      <ng-container i18n="@@fact.name.deleted" *ngSwitchCase="'Deleted'"
        ><span>Deleted</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.integrity-check"
        *ngSwitchCase="'IntegrityCheck'"
        ><span>IntegrityCheck</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.integrity-check-failed"
        *ngSwitchCase="'IntegrityCheckFailed'"
        ><span>IntegrityCheckFailed</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.lost-bicycle-node-tag"
        *ngSwitchCase="'LostBicycleNodeTag'"
        ><span>LostBicycleNodeTag</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.lost-hiking-node-tag"
        *ngSwitchCase="'LostHikingNodeTag'"
        ><span>LostHikingNodeTag</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.lost-route-tags"
        *ngSwitchCase="'LostRouteTags'"
        ><span>LostRouteTags</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.name-missing"
        *ngSwitchCase="'NameMissing'"
        ><span>NameMissing</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.network-extra-member-node"
        *ngSwitchCase="'NetworkExtraMemberNode'"
        ><span>NetworkExtraMemberNode</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.network-extra-member-relation"
        *ngSwitchCase="'NetworkExtraMemberRelation'"
        ><span>NetworkExtraMemberRelation</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.network-extra-member-way"
        *ngSwitchCase="'NetworkExtraMemberWay'"
        ><span>NetworkExtraMemberWay</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.node-member-missing"
        *ngSwitchCase="'NodeMemberMissing'"
        ><span>NodeMemberMissing</span>
      </ng-container>
      <ng-container i18n="@@fact.name.orphan-node" *ngSwitchCase="'OrphanNode'"
        ><span>OrphanNode</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.orphan-route"
        *ngSwitchCase="'OrphanRoute'"
        ><span>OrphanRoute</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-analysis-failed"
        *ngSwitchCase="'RouteAnalysisFailed'"
        ><span>RouteAnalysisFailed</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-broken"
        *ngSwitchCase="'RouteBroken'"
        ><span>RouteBroken</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-fixmetodo"
        *ngSwitchCase="'RouteFixmetodo'"
        ><span>RouteFixmetodo</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-incomplete"
        *ngSwitchCase="'RouteIncomplete'"
        ><span>RouteIncomplete</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-incomplete-ok"
        *ngSwitchCase="'RouteIncompleteOk'"
        ><span>RouteIncompleteOk</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-name-missing"
        *ngSwitchCase="'RouteNameMissing'"
        ><span>RouteNameMissing</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-node-missing-in-ways"
        *ngSwitchCase="'RouteNodeMissingInWays'"
        ><span>RouteNodeMissingInWays</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-node-name-mismatch"
        *ngSwitchCase="'RouteNodeNameMismatch'"
        ><span>RouteNodeNameMismatch</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-not-backward"
        *ngSwitchCase="'RouteNotBackward'"
        ><span>RouteNotBackward</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-not-continious"
        *ngSwitchCase="'RouteNotContinious'"
        ><span>RouteNotContinious</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-not-forward"
        *ngSwitchCase="'RouteNotForward'"
        ><span>RouteNotForward</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-not-one-way"
        *ngSwitchCase="'RouteNotOneWay'"
        ><span>RouteNotOneWay</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-one-way"
        *ngSwitchCase="'RouteOneWay'"
        ><span>RouteOneWay</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-overlapping-ways"
        *ngSwitchCase="'RouteOverlappingWays'"
        ><span>RouteOverlappingWays</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-redundant-nodes"
        *ngSwitchCase="'RouteRedundantNodes'"
        ><span>RouteRedundantNodes</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-reversed"
        *ngSwitchCase="'RouteReversed'"
        ><span>RouteReversed</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-suspicious-ways"
        *ngSwitchCase="'RouteSuspiciousWays'"
        ><span>RouteSuspiciousWays</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-tag-invalid"
        *ngSwitchCase="'RouteTagInvalid'"
        ><span>RouteTagInvalid</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-tag-missing"
        *ngSwitchCase="'RouteTagMissing'"
        ><span>RouteTagMissing</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-unaccessible"
        *ngSwitchCase="'RouteUnaccessible'"
        ><span>RouteUnaccessible</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-unexpected-node"
        *ngSwitchCase="'RouteUnexpectedNode'"
        ><span>RouteUnexpectedNode</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-unexpected-relation"
        *ngSwitchCase="'RouteUnexpectedRelation'"
        ><span>RouteUnexpectedRelation</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-unused-segments"
        *ngSwitchCase="'RouteUnusedSegments'"
        ><span>RouteUnusedSegments</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-without-nodes"
        *ngSwitchCase="'RouteWithoutNodes'"
        ><span>RouteWithoutNodes</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-without-ways"
        *ngSwitchCase="'RouteWithoutWays'"
        ><span>RouteWithoutWays</span>
      </ng-container>
      <ng-container i18n="@@fact.name.was-orphan" *ngSwitchCase="'WasOrphan'"
        ><span>WasOrphan</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.node-invalid-survey-date"
        *ngSwitchCase="'NodeInvalidSurveyDate'"
        ><span>NodeInvalidSurveyDate</span>
      </ng-container>
      <ng-container
        i18n="@@fact.name.route-invalid-survey-date"
        *ngSwitchCase="'RouteInvalidSurveyDate'"
        ><span>RouteInvalidSurveyDate</span>
      </ng-container>
      <ng-container *ngSwitchDefault>?{{ fact }}?</ng-container>
    </ng-container>
  `,
})
export class FactNameComponent {
  @Input() fact: Fact;
}
