package kpn.api.custom;

import org.junit.jupiter.api.Test;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class DayTest {

  @Test
  public void testFromString() {

    assertEquals(Day.fromString("2020-08-11"), Optional.of(new Day(2020, 8, 11)));
    assertEquals(Day.fromString("2020-08"), Optional.of(new Day(2020, 8)));

    assertEquals(Day.fromString("bla"), Optional.empty());
    assertEquals(Day.fromString("202a-08-11"), Optional.empty());
    assertEquals(Day.fromString("2020-0a-11"), Optional.empty());
    assertEquals(Day.fromString("2020-08-1a"), Optional.empty());
  }

  @Test
  public void testYyyymmdd() {
    assertEquals(new Day(2020, 8, 11).yyyymmdd(), "2020-08-11");
    assertEquals(new Day(2020, 8).yyyymmdd(), "2020-08");
  }
  // generated by AI:

  @Test
  public void testFromStringWithYearMonthDay() {
    Optional<Day> day = Day.fromString("2023-07-18");
    assertTrue(day.isPresent());
    assertEquals(2023, day.get().year());
    assertEquals(7, day.get().month());
    assertEquals(Optional.of(18), day.get().day());
  }

  @Test
  public void testFromStringWithYearMonth() {
    Optional<Day> day = Day.fromString("2023-07");
    assertTrue(day.isPresent());
    assertEquals(2023, day.get().year());
    assertEquals(7, day.get().month());
    assertEquals(Optional.empty(), day.get().day());
  }

  @Test
  public void testFromStringWithInvalidFormat() {
    Optional<Day> day = Day.fromString("invalid-input");
    assertTrue(day.isEmpty());

    day = Day.fromString("20230718");
    assertTrue(day.isEmpty());

    day = Day.fromString("2023-13-40");
    assertTrue(day.isEmpty());
  }
}
