package kpn.tools.code

import kpn.tools.code.codecs.Codecs
import kpn.tools.code.domain.ClassField
import kpn.tools.code.domain.ClassInfo
import kpn.tools.code.domain.ClassType

import java.io.File
import java.io.PrintStream

class CodecWriter {

  def write(classInfo: ClassInfo): Unit = {

    val file = createOutputFile(classInfo)
    val out = new IndentingPrintStream(new PrintStream(file))

    try {
      writeCodec(classInfo, out)
    }
    finally {
      out.close()
    }
  }

  private def writeCodec(classInfo: ClassInfo, out: IndentingPrintStream): Unit = {
    writeHeader(out)
    writeImports(out, classInfo)
    writeClassStart(out, classInfo)
    writeCodecs(out, classInfo)
    writeDecodeMethod(out, classInfo)
    writeEncodeMethod(out, classInfo)
    writeGetEncoderClassMethod(out, classInfo)
    out.println("}")
  }

  private def createOutputFile(classInfo: ClassInfo): File = {
    val file = new File(s"${Codecs.CodecDir}/${classInfo.className}Codec.scala")
    file.getParentFile.mkdirs()
    file
  }

  private def writeHeader(out: IndentingPrintStream): Unit = {
    out.println("// this file is generated by kpn.tools.code.CodecWriter")
    out.skipLine()
    out.println("package kpn.tools.code.codecs.generated")
  }

  private def writeImports(out: IndentingPrintStream, classInfo: ClassInfo): Unit = {
    val importClasses: Seq[String] = determineImportClasses(classInfo)
    out.skipLine()
    importClasses.foreach { className =>
      out.println(s"import $className")
    }
  }

  private def determineImportClasses(classInfo: ClassInfo) = {
    val fixedImportClasses = determineFixedImportClasses(classInfo)
    val importClass = s"${classInfo.packageName}.${classInfo.className}"
    val fieldImportClasses = determineFieldImportClasses(classInfo)
    val importClasses = (Seq(importClass) ++ fixedImportClasses ++ fieldImportClasses).sorted.distinct
    importClasses
  }

  private def determineFieldImportClasses(classInfo: ClassInfo) = {
    val classTypes = classInfo.fields.flatMap { field =>
      Seq(field.classType) ++
        field.classType.arrayType.toSeq ++
        field.classType.mapTypes.toSeq.flatMap(ee => Seq(ee._1, ee._2))
    }
    classTypes.flatMap { classType =>
      for {
        packageName <- classType.packageName
        typeName <- classType.typeName
      } yield s"$packageName.$typeName"
    }
  }

  private def determineFixedImportClasses(classInfo: ClassInfo) = {
    val bsonImports = Seq(
      "org.bson.BsonReader",
      "org.bson.BsonWriter",
      "org.bson.codecs.Codec",
      "org.bson.codecs.DecoderContext",
      "org.bson.codecs.EncoderContext",
      "org.bson.codecs.configuration.CodecRegistry",
    )
    if (classInfo.isEnum) {
      bsonImports
    }
    else {
      bsonImports ++ Seq(
        "kpn.tools.code.codecs.Codecs",
        "org.bson.BsonType",
      )
    }
  }

  private def writeClassStart(out: IndentingPrintStream, classInfo: ClassInfo): Unit = {
    out.skipLine()
    out.println(s"class ${classInfo.className}Codec(registry: CodecRegistry) extends Codec[${classInfo.className}] {")
  }

  private def writeCodecs(out: IndentingPrintStream, classInfo: ClassInfo): Unit = {
    val classTypes = classInfo.fields.flatMap { field =>
      field.classType.typeName.toSeq ++ field.classType.arrayType.toSeq.flatMap(_.typeName)
    }.sorted.distinct

    if (classTypes.nonEmpty) {
      out.skipLine()
    }

    classTypes.foreach { typeName =>
      val codecName = codecVariableName(typeName)
      out.println(s"  private val $codecName = registry.get(classOf[$typeName])")
    }
  }

  private def writeDecodeMethod(out: IndentingPrintStream, classInfo: ClassInfo): Unit = {

    out.skipLine()
    out.indent {
      out.println(s"override def decode(bsonReader: BsonReader, decoderContext: DecoderContext): ${classInfo.className} = {")
      out.indent {
        if (classInfo.isEnum) {
          writeEnumDecodeMethod(out, classInfo)
        }
        else {
          writeCaseClassDecodeMethod(out, classInfo)
        }
      }
      out.println("}")
    }
  }

  private def writeEnumDecodeMethod(out: IndentingPrintStream, classInfo: ClassInfo): Unit = {
    out.println(s"${classInfo.className}.withName(bsonReader.readString())")
  }

  private def writeCaseClassDecodeMethod(out: IndentingPrintStream, classInfo: ClassInfo): Unit = {
    out.println("bsonReader.readStartDocument()")
    out.skipLine()

    writeDecodeMethodVariableDeclarations(out, classInfo)
    writeDecodeMethodFields(out, classInfo)

    out.skipLine()
    out.println("bsonReader.readEndDocument()")
    out.skipLine()
    writeDecodeMethodClassInstanciation(out, classInfo)
  }

  private def writeDecodeMethodFields(out: IndentingPrintStream, classInfo: ClassInfo): Unit = {
    out.println("while (bsonReader.readBsonType != BsonType.END_OF_DOCUMENT) {")
    out.indent {
      out.println("val fieldName = bsonReader.readName")
      classInfo.fields.zipWithIndex.foreach { case (field, index) =>
        out.println(s"${if (index == 0) "" else "else "}if (fieldName == \"${field.name}\") {")
        out.indent {
          writeDecodeMethodField(out, field)
        }
        out.println("}")
      }
      out.println(s"else {")
      out.indent {
        out.println(s"Codecs.warn(s\"Unknown field name: $$fieldName in ${classInfo.className}Codec.decode()\")")
        out.println(s"bsonReader.skipValue()")
      }
      out.println(s"}")
    }
    out.println(s"}")
  }

  private def writeDecodeMethodField(out: IndentingPrintStream, field: ClassField): Unit = {
    field.classType.arrayType match {
      case Some(arrayType) =>

        arrayType.typeName match {
          case Some(typeName) =>
            writeDecodeMethodArrayField(out, field, typeName)
          case None =>
            out.println(s"Codecs.warn(\"${field.name} is an array of unknown type\")")
        }

      case None =>
        field.classType.typeName match {
          case Some(typeName) =>
            writeDecodeMethodFieldDecode(out, field, typeName)
          case None =>
            out.println(s"Codecs.warn(\"${field.name} is of unknown type\")")
        }
    }
  }

  private def writeDecodeMethodFieldDecode(out: IndentingPrintStream, field: ClassField, typeName: String): Unit = {
    val lowercaseTypeName = s"${typeName.head.toLower}${typeName.tail}"
    val codecName = codecVariableName(typeName)
    if (field.classType.optional) {
      out.println(s"${field.name} = Some($codecName.decode(bsonReader, decoderContext))")
    }
    else {
      out.println(s"${field.name} = $codecName.decode(bsonReader, decoderContext)")
    }
  }

  private def writeDecodeMethodArrayField(out: IndentingPrintStream, field: ClassField, typeName: String): Unit = {
    out.println(s"bsonReader.readStartArray()")
    out.println(s"val valueBuffer = scala.collection.mutable.Buffer[$typeName]()")
    out.println(s"while (bsonReader.readBsonType != BsonType.END_OF_DOCUMENT) {")
    out.indent {
      val codecName = codecVariableName(typeName)
      out.println(s"valueBuffer += $codecName.decode(bsonReader, decoderContext)")
    }
    out.println(s"}")
    out.println(s"bsonReader.readEndArray()")
    val value = s"valueBuffer.to${field.classType.arrayTypeClass.get}"
    val optionValue = if (field.classType.optional) {
      s"Some($value)"
    }
    else {
      value
    }
    out.println(s"${field.name} = $optionValue")
  }

  private def writeDecodeMethodClassInstanciation(out: IndentingPrintStream, classInfo: ClassInfo): Unit = {
    out.println(s"${classInfo.className}(")
    out.indent {
      classInfo.fields.foreach { field =>
        out.println(s"${field.name},")
      }
    }
    out.println(")")
  }

  private def writeDecodeMethodVariableDeclarations(out: IndentingPrintStream, classInfo: ClassInfo): Unit = {
    classInfo.fields.foreach { field =>
      val defaultValue = defaultValueForType(field.classType)
      out.println(s"var ${field.name}: ${field.typeString} = $defaultValue")
    }
    out.skipLine()
  }

  private def writeEncodeMethod(out: IndentingPrintStream, classInfo: ClassInfo): Unit = {
    out.skipLine()
    out.indent {
      out.println(s"override def encode(bsonWriter: BsonWriter, value: ${classInfo.className}, encoderContext: EncoderContext): Unit = {")
      out.indent {
        if (classInfo.isEnum) {
          out.println("bsonWriter.writeString(value.entryName)")
        }
        else {
          out.println("bsonWriter.writeStartDocument()")
          writeEncodeMethodFields(out, classInfo)
          out.skipLine()
          out.println("bsonWriter.writeEndDocument()")
        }
      }
      out.println("}")
    }
  }

  private def writeEncodeMethodFields(out: IndentingPrintStream, classInfo: ClassInfo): Unit = {
    classInfo.fields.foreach { field =>
      out.skipLine()
      if (field.classType.optional) {
        out.println(s"if (value.${field.name}.isDefined) {")
        out.indent {
          writeEncodeMethodField(out, field)
        }
        out.println("}")
      }
      else {
        writeEncodeMethodField(out, field)
      }
    }
  }

  private def writeEncodeMethodField(out: IndentingPrintStream, field: ClassField): Unit = {
    out.println(s"bsonWriter.writeName(\"${field.name}\")")

    field.classType.arrayType match {
      case Some(arrayType) =>

        arrayType.typeName match {
          case Some(typeName) =>
            writeEncodeMethodArrayField(out, field, typeName)

          case None =>
            out.println(s"Codecs.warn(\"${field.name} is of unknown type\")")
        }

      case None =>
        field.classType.typeName match {
          case Some(typeName) =>
            val codecName = codecVariableName(typeName)
            val value = if (field.classType.optional) {
              s"value.${field.name}.get"
            }
            else {
              s"value.${field.name}"
            }
            out.println(s"$codecName.encode(bsonWriter, $value, encoderContext)")
          case None =>
            out.println(s"Codecs.warn(\"${field.name} is of unknown type\")")
        }
    }
  }

  private def writeEncodeMethodArrayField(out: IndentingPrintStream, field: ClassField, typeName: String): Unit = {
    val codecName = codecVariableName(typeName)
    out.println(s"bsonWriter.writeStartArray()")
    val value = if (field.classType.optional) {
      s"value.${field.name}.get"
    }
    else {
      s"value.${field.name}"
    }
    out.println(s"$value.foreach(v => $codecName.encode(bsonWriter, v, encoderContext))")
    out.println(s"bsonWriter.writeEndArray()")
  }

  private def writeGetEncoderClassMethod(out: IndentingPrintStream, classInfo: ClassInfo): Unit = {
    out.skipLine()
    out.indent {
      out.println(s"override def getEncoderClass: Class[${classInfo.className}] = {")
      out.indent {
        out.println(s"classOf[${classInfo.className}]")
      }
      out.println(s"}")
    }
  }

  private def codecVariableName(typeName: String): String = {
    s"${typeName.head.toLower}${typeName.tail}Codec"
  }

  private def defaultValueForType(classType: ClassType): String = {
    if (classType.optional) {
      "None"
    } else if (classType.typeName.contains("Long") ||
      classType.typeName.contains("Int") ||
      classType.typeName.contains("Double")) {
      "0"
    } else if (classType.typeName.contains("Boolean")) {
      "false"
    } else {
      "null"
    }
  }
}
