package kpn.api.common

enum Fact:
  case RouteUnsupportedRouteType,
    // errors
    RouteNotContinious,
    RouteNotForward,
    RouteNotBackward,
    RouteUnusedSegments,
    RouteNodeMissingInWays,
    RouteRedundantNodes,
    RouteWithoutWays,
    RouteWithoutNodes,
    RouteFixmetodo,
    RouteNameMissing,
    RouteTagMissing,
    RouteTagInvalid,
    RouteUnexpectedNode,
    RouteUnexpectedRelation,
    NetworkExtraMemberNode,
    NetworkExtraMemberWay,
    NetworkExtraMemberRelation,
    NodeMemberMissing,
    IntegrityCheckFailed,
    UnexpectedIntegrityCheck,
    NameMissing,
    OrphanRoute,
    OrphanNode,
    RouteOverlappingWays,
    RouteSuspiciousWays,
    RouteAnalysisFailed,
    
    // informational
    RouteIncomplete,
    RouteInaccessible,
    RouteInvalidSortingOrder,
    RouteNodeNameMismatch,
    RouteNameDeprecatedNoteTag,
    RouteOneWay,
    RouteNotOneWay,
    RouteIncompleteOk,
    
    // other
    RouteBroken,
    IntegrityCheck,
    Added,
    Deleted,
    LostHikingNodeTag,
    LostBicycleNodeTag,
    LostRouteTags,
    LostHorseNodeTag,
    LostMotorboatNodeTag,
    LostCanoeNodeTag,
    LostInlineSkateNodeTag,
    NodeInvalidSurveyDate,
    RouteInvalidSurveyDate,
    NetworkInvalidSurveyDate
