package kpn.server.analyzer.engine.analysis.location

// 83 communes https://www.parc-du-vercors.fr/le-perimetre-et-les-chiffres-cles
object ParcDuVercors {

  val communes: Seq[String] = Seq(
    "Auberives-en-Royans",
    "Autrans-Méaudre en Vercors",
    "Beaufort-sur-Gervanne",
    "Beauvoir-en-Royans",
    "Bouvante",
    "Chamaloc",
    "Château-Bernard",
    "Châtelus",
    "Châtillon-en-Diois",
    "Chichilianne",
    "Choranche",
    "Claix",
    "Clelles",
    "Cognin-les-Gorges",
    "Combovin",
    "Corrençon-en-Vercors",
    "Die",
    "Échevis",
    "Engins",
    "Fontaine",
    "Gigors-et-Lozeron",
    "Glandage",
    "Gresse-en-Vercors",
    "Izeron",
    "La Chapelle-en-Vercors",
    "La Motte-Fanjas",
    "La Rivière",
    "Lans-en-Vercors",
    "Laval-d'Aix",
    "Le Chaffal",
    "Le Gua",
    "Léoncel",
    "Lus-la-Croix-Haute",
    "Malleval-en-Vercors",
    "Marignac-en-Diois",
    "Miribel-Lanchâtre",
    "Le Monestier-du-Percy",
    "Percy",
    "Montaud",
    "Noyarey",
    "Omblèze",
    "Oriol-en-Royans",
    "Plan-de-Baix",
    "Ponet-et-Saint-Auban",
    "Pont-en-Royans",
    "Presles",
    "Rencurel",
    "Rochechinard",
    "Romeyer",
    "Rovon",
    "Sassenage",
    "Seyssinet-Pariset",
    "Seyssins",
    "Saint-Agnan-en-Vercors",
    "Saint-Andéol",
    "Saint-Andéol",
    "Saint-André-en-Royans",
    "Saint-Gervais",
    "Saint-Guillaume",
    "Saint-Jean-en-Royans",
    "Saint-Julien-en-Quint",
    "Saint-Julien-en-Vercors",
    "Saint-Just-de-Claix",
    "Saint-Laurent-en-Royans",
    "Saint-Martin-de-Clelles",
    "Saint-Martin-en-Vercors",
    "Saint-Martin-le-Colonel",
    "Saint-Michel-les-Portes",
    "Saint-Nazaire-en-Royans",
    "Saint-Nizier-du-Moucherotte",
    "Saint-Paul-lès-Monestier",
    "Saint-Pierre-de-Chérennes",
    "Saint-Quentin-sur-Isère",
    "Saint-Romans",
    "Saint-Thomas-en-Royans",
    "Saint-Paul-de-Varces",
    "Sainte-Croix",
    "Sainte-Eulalie-en-Royans",
    "Vachères-en-Quint",
    "Varces-Allières-et-Risset",
    "Vassieux-en-Vercors",
    "Veurey-Voroize",
    "Villard-de-Lans"
  )
}
