== Analyse

=== Mappen


==== rwn

__R__egional __W__alking __N__etwork

(regionaal wandelnetwerk)


==== rcn

__R__egional __C__ycle __N__etwork

(regionaal fietsnetwerk)


==== Knooppunt

...


==== Netwerkrelatie

Relatie met knoopunten en routes.

Een wandelnetwerk relatie heeft minimaal de volgende tags:

[cols="1,1,4"]
|===
|Sleutel|Waarde|Commentaar

|network
|rwn
|rwn = regional walking network

|type
|network
|

|name
|_naam_
|netwerk naam
|===

Een fietsnetwerk relatie heeft minimaal de volgende tags:

[cols="1,1,4"]
|===
|Sleutel
|Waarde
|Commentaar

|network
|rcn
|rcn = regional cyclde network

|type
|network
|

|name
|_naam_
|netwerk naam
|===



==== Route relatie


Een route relatie bevat de wegen die de knooppunten met elkaar verbinden, en optioneel ook de
knopen van de knooppunten zelf.

Een wandelnetwerk route relatie heeft minimaal de volgende tags:

[cols="1,1,4"]
|===
|Sleutel
|Waarde
|Commentaar

|network
|rwn
|rwn = regional walking network

|type
|route
|

|route
|foot
|In plaats van _foot_ laat de analyse logica ook de waarden _hiking en _walking_ toe.

|note
|_naam_
|We verwachten dat de route naam  wordt samengesteld uit de namen van het start knooppunt en het eind knooppunt, van elkaar gescheiden
door een koppelteken. Bijvoorbeeld: de naam van de met start knooppunt _23_ en eindknooppunt _68_ is: _23-68_.
|===


Een fietsnetwerk route relatie heeft minimaal de volgende tags:

[cols="1,1,4"]
|===
|Sleutel
|Waarde
| Commentaar

|network
|rcn
|rcn = regional cycling network

|type
|route
|

|route
|bicycle
|

|note
|_naam_
|route naam
|===


==== Knooppuntwees

Een _knooppunt wees_ is een knooppunt waarvan we niet weten bij welk knooppuntnetwerk
het hoort.

We kunnen zien dat de knoop een knooppunt is uit een knooppuntennetwerk omdat er een tag
met sleutel *"rwn_ref"* of *"rcn_ref"* is, maar deze knoop werd niet toegevoegd
aan een netwerk- of een routerelatie.

Indien er iets mis is met de relatie waaraan de knoop werd toegevoegd (bijvoorbeeld omdat de
relatie niet voldoet aan de regels voor een geldige netwerk- of routerelatie), dan wordt
het knooppunt ook beschouwd als _"wees"_.



==== Route wees


Een _route wees_ is een route waarvan we niet weten bij welk knooppuntnetwerk die hoort.

De relatie wordt herkend als een geldige knooppuntnetwerkroute, maar de relatie werd niet
toegevoegd in een gekende en geldige netwerkrelatie.

Als er iets mis is met de netwerk relatie waaraan de route relatie toegevoegd is, dan wordt de route
ook als _"wees"_ beschouwd.



==== Informatie bord


Verspreid over het netwerk bevinden er zich vaak informatie borden met daarop
een kaart van het netwerk en wat verdere toelichting. Deze borden kunnen gemapped
worden door middel van knopen. Deze knopen kunnen eventueel toegevoegd worden
in de netwerk relatie. De analyse logica verwacht dat de knoop ten minste de
volgende tags bevat:

[cols="1,4"]
|===
|Sleutel|Waarde

|tourism
|information

|information
|map
|===


==== Toegankelijk

De analyse logica probeert na te gaan of de routes in het knooppuntennetwerk ook daadwerkelijk
toegankelijk zijn voor de gebruiker waar het netwerk voor bedoeld is.

Een weg (way) in een wandel-, fiets-, ruiter-, of skateroute wordt als _"toegankelijk"_ beschouwd indien
aan minstens 1 van de volgende voorwaarden voldaan is:

* De weg heeft een tag met sleutel _"highway"_ of  _"highway:virtual"_.
* De weg heeft een tag met sleutel _"route"_ en waarde _"ferry"_.
* De weg in een fietsnetwerk heeft een tag met sleutel _"bicycle"_ en waarde _"yes"_.
* De weg in een wandelnetwerk heeft een tag met sleutel _"foot"_ en waarde _"yes"_.
* De weg in een ruiternetwerk heeft een tag met sleutel _"horse"_ en waarde _"yes"_.
* De weg in een skatenetwerk heeft een tag met sleutel _"inline_skates"_ en waarde _"yes"_.

Motorboot netwerk:

* De weg heeft een tag met sleutel _"waterway"_ of  _"waterway:virtual"_.

Kano netwerk, minstens 1 van:

* De weg heeft een tag met sleutel _"waterway"_ of  _"waterway:virtual"_.
* De weg heeft een tag met sleutel _"canoe"_ en waarde  _"yes"_.
* De weg heeft een tag met sleutel _"canoe"_ en waarde  _"portage"_.

