package kpn.server.json

case class JsonLargeExample(
  field01: String = "",
  field02: String = "",
  field03: String = "",
  field04: String = "",
  field05: String = "",
  field06: String = "",
  field07: String = "",
  field08: String = "",
  field09: String = "",
  field10: String = "",
  field11: String = "",
  field12: String = "",
  field13: String = "",
  field14: String = "",
  field15: String = "",
  field16: String = "",
  field17: String = "",
  field18: String = "",
  field19: String = "",
  field20: String = "",
  field21: String = "",
  field22: String = "",
  field23: String = "",
  field24: String = "",
  field25: String = "",
  field26: String = "",
  field27: String = "",
  field28: String = "",
  field29: String = "",
  field30: String = "",
  field31: String = "",
  field32: String = "",
  field33: String = "",
  field34: String = "",
  field35: String = "",
  field36: String = "",
  field37: String = "",
  field38: String = "",
  field39: String = "",
  field40: String = "",
)
