[#contribute]
== How to contribute?

Here are a number of ways of how to contribute to the project:

- validate routes on the ground

- map additional nodes/routes/networks

- report errors

- application translation

- documentation

- application testing

- application code


[#translations]
=== Help translating the application to different languages

The intention is to have _knooppuntnet_ available in four languages: English, Dutch, German and French.

Your help in translating the application to a language that is not fully translated yet, or
to fix wrong translations, is very welcome.

The base language for the application is English. Support for translation to the other languages
is kindly provided free of charge by https://poeditor.com[POEditor]. POEditor supports
open source. Many thanks!!!

Follow this https://poeditor.com/join/project/Bfvs2fvcYI[link] to join the knooppuntnet translation project.

From the project start page you can select the language. In the _"Translations"_ tab you can review all translations
(select _"Show: translated"_), or bring up the list with all texts that still need translation (select _"Show: Untranslated"_).
From these lists the translated texts can be entered and/or changed. Click the text to start editing.

All the translations you make here will appear in the knooppuntnet website in the next release.

The above is sufficient to help out with the translations.

A bit more advanced: if you like to review your translation changes without waiting for the next release,
you can follow the instructions in the section _"Install application locatlly"_ below.

In the POEditor page for your language, you can go to the _"Export"_ tab.  Select _"Show Advanced Options"_.
Select _"Export: All"_ and _"Filename: translations.XX.xlf"_ where XX is the 2 letter code for given language:

|===
|Language|Command

|Dutch
|translations.nl.xlf

|German
|translations.de.xlf

|French
|translations.fr.xlf
|===

Klik _"Export"_ and save the file in the _"locale"_ directory in your git clone:

	knooppuntnet/client/src/locale

To see your translations in action, restart the application in development for given
language, for example:

	yarn run start:de

Note: changes to the English texts have to be done directly in the application code.

[#install-application-locally]
=== Install application locally

These are the instructions for installing the client application on your local computer.


==== yarn

We use https://yarnpkg.com[yarn] to manage the software dependencies and to help in installing
and running the client application.

Go to https://yarnpkg.com, click the install button, and follow the
instructions for your operating system.

==== git

We use git as our version control system. Although it is also possible to download
the code as a zip file, it will be easier to immediately use git, especially if the
intention is to contribute to the project afterwards.

Go to https://git-scm.com/downloads[git downloads] and follow the installation instructions.


==== Install and run

Get the source code:

	git clone https://github.com/vmarc/knooppuntnet.git

Install the software and fetch all dependencies:

	cd knooppuntnet/client/
	yarn install

Build and run the client:

	yarn run start:en

The above command will build and start the English version of the application in development mode.
Use one of the following commands to start the application in another language:

[cols="1,3"]
|===
|Language|Command

|English
|yarn run start:en

|Dutch
|yarn run start:nl

|German
|yarn run start:de

|French
|yarn run start:fr
|===


When starting the application in a language other than English, the texts that are not translated yet are shown in English.


[#update-documentation]
=== Update documentation

The documentation is written in https://asciidoctor.org/docs/[asciidoc], maven is used for installing the
required software and building the documentation.

==== Install maven

Follow instructions on http://maven.apache.org/ to download and install maven.


==== Get the source code

Go to https://git-scm.com/downloads[git downloads] and follow the installation instructions (see also above).

Get the source code:

	git clone https://github.com/vmarc/knooppuntnet.git


==== Build the documentation

To build the documentation, run the following commands:

	cd knooppuntnet/docs/guide
	mvn compile

After running these commands, you can find the html and pdf documentation in following directories:

	knooppuntnet/docs/guide/target/html
	knooppuntnet/docs/guide/target/pdf

The sources for the documentation can be found here:

	knooppuntnet/docs/src/main/asciidoc

After updating the documentation sources, you can rebuild the documentation:

	cd knooppuntnet/docs
	mvn compile

Commit your changes to git. The updated documentation will appear on the web-site with the next release.
Until we have a better publishing mechanism, send a message to https://www.openstreetmap.org/user/vmarc[vmarc]
to ask for deploying a new release of the documentation.
