package kpn.core.poi

object PoiConfiguration {

  val poiDefinitionGroups = Seq(
    PoiDefinitionGroup(
      "amenity",
      PoiDefinition("atm", "[amenity=atm]", "[amenity=bank][atm][atm!=no]"),
      PoiDefinition("bank", "[amenity=bank]"),
      PoiDefinition("bench", "[amenity=bench]"), // original: only node
      PoiDefinition("bicycle_parking", "[amenity=bicycle_parking]"),
      PoiDefinition("bicycle_rental", "[amenity=bicycle_rental]"),
      PoiDefinition("cinema", "[amenity=cinema]"),
      PoiDefinition("clinic", "[amenity=clinic]"),
      PoiDefinition("embassy", "[amenity=embassy]"),
      PoiDefinition("firestation", "[amenity=firestation]"),
      PoiDefinition("fuel", "[amenity=fuel]"),
      PoiDefinition("hospital", "[amenity=hospital]"),
      PoiDefinition("library", "[amenity=library]"),
      PoiDefinition("music_school", "[amenity=music_school]"),
      PoiDefinition("parking", "[amenity=parking]"),
      PoiDefinition("pharmacy", "[amenity=pharmacy]"),
      PoiDefinition("police", "[amenity=police]"),
      PoiDefinition("post_box", "[amenity=post_box]"), // only node
      PoiDefinition("post_office", "[amenity=post_office]"),
      PoiDefinition("school_college", "[amenity~'^school$|^college$']"),
      PoiDefinition("taxi", "[amenity=taxi]"),
      PoiDefinition("theatre", "[amenity=theatre]"),
      PoiDefinition("toilets", "[amenity=toilets]"),
      PoiDefinition("university", "[amenity=university]"),
      PoiDefinition("place_of_worship", "[amenity=place_of_worship][religion!~'christian|muslim|buddhist|hindu|jewish']"),
      PoiDefinition("church", "[amenity=place_of_worship][religion=christian]"),
      PoiDefinition("mosque", "[amenity=place_of_worship][religion=muslim]"),
      PoiDefinition("buddhist_temple", "[amenity=place_of_worship][religion=buddhist]"),
      PoiDefinition("hindu_temple", "[amenity=place_of_worship][religion=hindu]"),
      PoiDefinition("synagogue", "[amenity=place_of_worship][religion=jewish]"),
      PoiDefinition("cemetery", "[landuse=cemetery][animal!~'.']")
    ),
    PoiDefinitionGroup(
      "tourism",
      PoiDefinition("arts centre", "[amenity=arts_centre]"),
      PoiDefinition("artwork", "[tourism=artwork][artwork_type!~'statue']"),
      PoiDefinition("attraction", "[tourism=attraction]"),
      PoiDefinition("casino", "[leisure=casino]"),
      PoiDefinition("castle", "[historic=castle]"),
      PoiDefinition("gallery", "[tourism=gallery]"),
      PoiDefinition("heritage", "[heritage]"),
      PoiDefinition("historic", "[historic][historic!~'memorial|monument|statue|castle']"), // Check for all historic tags but exclude those that already have their own
      PoiDefinition("information", "[tourism=information]"), // no rel
      PoiDefinition("monument_memorial", "[historic~'^monument$|^memorial$']"),
      PoiDefinition("monumental_tree", "[natural=tree][monument=yes]"), // only node
      PoiDefinition("museum", "[tourism=museum]"),
      PoiDefinition("picnic", "[tourism=picnic_site]", "[leisure=picnic_table]"), // picnic_table only node
      PoiDefinition("statue", "[historic=statue]"),
      PoiDefinition("theme_park", "[tourism=theme_park]"),
      PoiDefinition("viewpoint", "[tourism=viewpoint]"),
      PoiDefinition("vineyard", "[landuse=vineyard]"),
      PoiDefinition("windmill", "[man_made=windmill]"),
      PoiDefinition("watermill", "[man_made=watermill]"),
      PoiDefinition("zoo", "[tourism=zoo]"),
      PoiDefinition("tourism", "[tourism=yes]") // TODO review instances of this poi
    ),
    PoiDefinitionGroup(
      "places_to_stay",
      PoiDefinition("alpine_hut", "[tourism=alpine_hut]"),
      PoiDefinition("apartment", "[tourism=apartment]"),
      PoiDefinition("camp_site", "[tourism=camp_site][backcountry!=yes]"),
      PoiDefinition("chalet", "[tourism=chalet]"),
      PoiDefinition("guest_house", "[tourism~'guest_house|bed_and_breakfast']"),
      PoiDefinition("hostel", "[tourism=hostel]"),
      PoiDefinition("hotel", "[tourism=hotel]"),
      PoiDefinition("motel", "[tourism=motel]"),
      PoiDefinition("casino", "[amenity=casino]"),
      PoiDefinition("spa", "[leisure=spa]"),
      PoiDefinition("sauna", "[leisure=sauna]")
    ),
    PoiDefinitionGroup(
      "sport",
      PoiDefinition("american_football", "[sport=american_football]"),
      PoiDefinition("baseball", "[sport=baseball]"),
      PoiDefinition("basketball", "[sport=basketball]"),
      PoiDefinition("cycling", "[sport=cycling]"),
      PoiDefinition("gymnastics", "[sport=gymnastics]"),
      PoiDefinition("golf", "[leisure=golf_course]", "[sport=golf]"),
      PoiDefinition("hockey", "[sport=hockey]", "[sport=field_hockey]"),
      PoiDefinition("horse_racing", "[sport=horse_racing]", "[sport=equestrian]"),
      PoiDefinition("ice_hockey", "[sport=ice_hockey]", "[leisure=ice_rink]"),
      PoiDefinition("soccer", "[sport=soccer]"),
      PoiDefinition("sports_centre", "[leisure=sports_centre]"),
      PoiDefinition("surfing", "[sport=surfing]"),
      PoiDefinition("swimming", "[sport=swimming]"),
      PoiDefinition("tennis", "[sport=tennis]"),
      PoiDefinition("volleyball", "[sport=volleybal]")
    ),
    PoiDefinitionGroup(
      "shops",
      PoiDefinition("beauty", "[shop=beauty]"),
      PoiDefinition("bicycle", "[shop=bicycle]"),
      PoiDefinition("books_stationary", "[shop~'books|stationary']"),
      PoiDefinition("car", "[shop=car]"),
      PoiDefinition("chemist", "[shop=chemist]"),
      PoiDefinition("clothes", "[shop=clothes]"),
      PoiDefinition("copyshop", "[shop=copyshop]"),
      PoiDefinition("cosmetics", "[shop=cosmetics]"),
      PoiDefinition("department_store", "[shop=department_store]"),
      PoiDefinition("diy_hardware", "[shop~'doityourself|hardware']"),
      PoiDefinition("garden_centre", "[shop=garden_centre]"),
      PoiDefinition("general", "[shop=general]"),
      PoiDefinition("gift", "[shop=gift]"),
      PoiDefinition("hairdresser", "[shop=hairdresser]"),
      PoiDefinition("jewelry", "[shop~'jewelry|jewellery']"),
      PoiDefinition("kiosk", "[shop=kiosk]"),
      PoiDefinition("leather", "[shop=leather]"),
      PoiDefinition("marketplace", "[amenity=marketplace]"),
      PoiDefinition("musical_instrument", "[shop=musical_instrument]"),
      PoiDefinition("optician", "[shop=optician]"),
      PoiDefinition("pets", "[shop=pets]"),
      PoiDefinition("phone", "[shop=mobile_phone]"),
      PoiDefinition("photo", "[shop=photo]"),
      PoiDefinition("shoes", "[shop=shoes]"),
      PoiDefinition("shopping_centre", "[shop=mall]"),
      PoiDefinition("textiles", "[shop=textiles]"),
      PoiDefinition("toys", "[shop=toys]")
    ),
    PoiDefinitionGroup(
      "food_shops",
      PoiDefinition("alcohol", "[shop=alcohol]"),
      PoiDefinition("bakery", "[shop=bakery]"),
      PoiDefinition("beverages", "[shop=beverages]"),
      PoiDefinition("butcher", "[shop=butcher]"),
      PoiDefinition("cheese", "[shop=cheese]"),
      PoiDefinition("chocolate", "[shop=chocolate]"),
      PoiDefinition("confectionery", "[shop=confectionery]"),
      PoiDefinition("coffee", "[shop=coffee]"),
      PoiDefinition("dairy", "[shop=dairy]"),
      PoiDefinition("deli", "[shop=deli]"),
      PoiDefinition("drinking_water", "[amenity=drinking_water]"),
      PoiDefinition("grocery", "[shop=grocery]"),
      PoiDefinition("organic", "[shop=organic]"),
      PoiDefinition("seafood", "[shop=seafood]"),
      PoiDefinition("supermarket", "[shop=supermarket]"),
      PoiDefinition("wine", "[shop=wine]")
    ),
    PoiDefinitionGroup(
      "restaurants",
      PoiDefinition("bar", "[amenity=bar]"),
      PoiDefinition("bbq", "[amenity=bbq]"),
      PoiDefinition("biergarten", "[amenity=biergarten]"),
      PoiDefinition("cafe", "[amenity=cafe]"),
      PoiDefinition("fast_food", "[amenity=fast_food]"),
      PoiDefinition("food_court", "[amenity=food_court]"),
      PoiDefinition("ice_cream", "[amenity=ice_cream]", "[cuisine=ice_cream]"),
      PoiDefinition("pub", "[amenity=pub]"),
      PoiDefinition("restaurant", "[amenity=restaurant]")
    ),
    PoiDefinitionGroup(
      "various",
      // PoiDefinition("bus_stop", "[highway=bus_stop]"),
      PoiDefinition("ebike_charging", "[amenity=charging_station][bicycle=yes]"),
      // PoiDefinition("childcare", "[amenity~'childcare|kindergarten']"),
      PoiDefinition("marketplace", "[amenity=marketplace]"),
      // PoiDefinition("office", "[office]"),
      // PoiDefinition("recycling", "[amenity=recycling]"),
      PoiDefinition("travel_agency", "[shop=travel_agency]"),
      PoiDefinition("defibrillator", "[emergency=defibrillator]")
    )
  )
}
